//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medico
    {
        public string id_medico { get; set; }
        public string nom_medico { get; set; }
        public string especialidad { get; set; }
        public string tel_medico { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
