//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        public string id_paciente { get; set; }
        public string tip_doc { get; set; }
        public string nom_paciente { get; set; }
        public string dir_paciente { get; set; }
        public string tel_paciente { get; set; }
        public string cel_paciente { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
